server {
    listen 80;
    server_name localhost;
    root /srv/data;

    location / {
        autoindex on;
        autoindex_format json;
        try_files $uri $uri/ =404;

        sub_filter_once off;
        sub_filter_types application/json;

        if ($request_uri = /) {
            rewrite ^ /___index.html last;
        }

        if (-d $request_filename) {
            rewrite ^ /___index.html last;
        }
    }

    location = /___index.html {
        alias /usr/share/nginx/html/index.html;
    }

    location /___api/ {
        alias /srv/data/;
        autoindex on;
        autoindex_format json;
    }

    location = /___search {
        gzip off;
        fastcgi_pass unix:/var/run/fcgiwrap.sock;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /usr/lib/cgi-bin/search.cgi;
    }
}
